package com.giovane.soccer.commons;

public enum Position {
    GOALKEEPER, CENTRE_BACK, LEFT_FULLBACK, RIGHT_FULLBACK, ATTACKING_MID,
    DEFENSIVE_MID, CENTER_MID, LEFT_MID, RIGHT_MID, STRIKER, CENTER_FORWARD,
    WINGERS
}
